import arlpy.uwapm as pm
import arlpy.plot as plt
# Load a 3D .RAY file (generated by BELLHOP3D)

bh = pm._Bellhop()
rays = bh._load_rays('../mantaray/cmake-build-release/src/background_ray')
arrivals = bh._load_arrivals('../mantaray/cmake-build-release/src/background_ray')
# Plot the rays
# pm.plot_rays(rays, width=900)   
pm.plot_arrivals(arrivals,)
